mqtt:
  hostname: 192.168.178.63  # MQTT broker within home assistant
  port: 1883                # defaults to 1883
deviceName: walli7
client_id: some_other_client
timezone: Europe/Brussels
update_interval: 60       # Defaults to 60
